// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjljzqxoihzscumwvctd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqbGp6cXhvaWh6c2N1bXd2Y3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTE1MTksImV4cCI6MjA3MTI4NzUxOX0.It5wYd3chZtf5txKpFUYVrcCGaVX42xXwC83243tDzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});